import pandas
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from mpl_toolkits.mplot3d import Axes3D
import sys

from read_data import *
from plot_data import *

f_name = sys.argv[1]

fig = plt.figure()
fig.set_size_inches(17, 9)

lag_len_weeks = 1

gs = gridspec.GridSpec(1, 3, width_ratios=[1, 1, 0.1])

df = read_file(f_name)
m = max(find_max_val(df, "Entries_CC"), find_max_val(df, "Exits_CC"))
fig.suptitle("3D Lag Plot For Tennessee CC (Autogenerated) Lag="+str(lag_len_weeks)+" weeks")
ax = plt.subplot(gs[0], projection='3d')
plot = plot_data(ax, "Entries_CC", "CC Entries", process_df(df, "Entries_CC", lag_len_weeks), seasonal=False)

ax2 = plt.subplot(gs[1], projection='3d')
plot2 = plot_data(ax2, "Exits_CC", "CC Exits", process_df(df, "Exits_CC", lag_len_weeks), seasonal=False)

set_all_maxes(ax, m)
set_all_maxes(ax2, m)

cbaxes = plt.subplot(gs[2])
fig.colorbar(plot2, cax=cbaxes, label="Time in weeks")

fig.savefig("test_TN_CC.png", dpi=300, transparent=True, bbox_inches='tight')
plt.tight_layout()
plt.show()
